### ISSUE TITLE
generate only ".d.ts "

### ISSUE THREAD

**Issue by jenwirth** [scala-ts/scala-ts#1287]
Hi,

I think I have a different use case then this project's goal. I just wanted to make sure. We use tapir for our backend and also use it to generate a scalajs client module and publish this as a npm package.  This module will then be used by typescript front-end developers. I believe the difference between this project and our need, is that we have implemented the scalajs client and just would want to include `d.ts` files next to the compiled js.

Is this something that could be accomplished using this project?

**Comment by cchantep** [comment]
Hi,

Not really.
Scala-TS doesn't only generate export, but also utilities around types that are required to have something operational.

There is a lot of examples and demo in the documentation : https://scala-ts.github.io/scala-ts/
