### ISSUE TITLE
Is it possible to generate methods?

### ISSUE THREAD

**Issue by user753** [scala-ts/scala-ts#1332]
I want to use scala-ts as d.ts generator from scala.js code
For example, I have
```
case class Foo(x: Int) {
   def calc(y: Int): Int = x + y
}
```
I would like to generate 
```ts
export interface Foo {
  x: Int
  calc: (y: Int) => Int
}

```
Is it possible?

**Comment by cchantep** [comment]
Scala-TS is not Scala.js, it only transpile datamodel related code.
There is no plan to go further (and so to overlap with Scala.js).

**Comment by user753** [comment]
This feature looks very close to the current functionality of scala-ts. All it needs is convert method definitions to interface members with function type.
So, it's not possible to achieve this with some custom `DeclarationMappers` or `TypeMappers`?

**Comment by cchantep** [comment]
You can do what you what with the mapper, but Scala-TS doesn't aim to transpile code outside datamodel.
