### ISSUE TITLE
Scala 3 Support?

### ISSUE THREAD

**Issue by dejvid** [scala-ts/scala-ts#1386]
Hi everyone, will there be a public Scala 3  build version of this library? I see that you are still active, I wonder if this is happening any time soon? I would like to export type definitions of projects in Scala 3 which will expose some API stuff to the typescript environment. And this scala-ts is just the right tool to do it. Do you have roadmap for Scala 3 release? Are you close? I would like to know :) Or maybe there is something I can help with, maybe testing if it works fine ;)

**Comment by cchantep** [comment]
Hi,

It's already supported.
