### ISSUE TITLE
Resolving classes from submodules

### ISSUE THREAD

**Issue by NPCRUS** [scala-ts/scala-ts#1579]
I have a multi-module setup with a following structure:

- commons
- api1 depends on commons
- api2 depends on commons

There are plenty of enums and generic ADTs that reside in commons, because they are used in both apis
I was fighting for quite a while, but didn't find if it's possible to include class from dependent project into scalats compilation pipeline. In the end I would have *.ts file like this one:
```
import SomeEnum from './SomeEnum.ts'

interface SomeEntity {
  field: string
  field2: SomeEnum
}
```
But the `SomeEnum.ts` doesn't exist and not resolved.
I would appreciate if you could give me some directions for this investigation, in case I'm missing something. Otherwise I would be more than happy to discuss and/or implement possible solution if it's part of the project scope

**Comment by cchantep** [comment]
Without a complete reproducer there is no way to answer.

**Comment by NPCRUS** [comment]
@cchantep, thanks for answeringI made a small repo to reproduce it https://github.com/NPCRUS/scalats-reproduce and I added couple of examples of data structures from `commons` module being used in some structures in `api` module:
- enum
- case class
- case class with type param
- ADT using trait
The result I'm experiencing is that scalats generates all classes from `api` module, all structures from `commons` were not generated except `CaseClassWithTypeParam`.
One could argue that I might just add scalats plugin into `commons` module and then merge target directories, but since case class with type param is generated - it seems more like a bug.
I hope my example is sufficient, let me know if you need more information!

**Comment by cchantep** [comment]
If there is a bug, it's that `CaseClassWithTypeParam` must not be generated.
Anyway if you want the types in `commons` to be generated, you have to enable the plugin on this module.

**Comment by cchantep** [comment]
Moreover:
- `ADT` is not valid as not sealed.
- `SimpleCaseClass` is an empty/invalid class (not case)

**Comment by NPCRUS** [comment]
I see. Thanks for response!
