### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by nicolasdalsass** [scala-ts/scala-ts#21]
Hi,

I just wanted to let you now that we (Elium.tv) are maintaining a fork of this lib. We have diverged some commits ago regarding implementation of common needs (like sealed traits handling), but some people may find it useful :+1: 

Nevertheless, thanks for  the time you contributed maintaining this project, it definitely helped us !

**Comment by zhenwenc** [comment]
Hi @nicolasdalsass , I am wondering are you still maintaining the fork of this lib, since there is no commit in the past 9 months. Or have you found any good alternatives? Many thanks!

**Comment by nicolasdalsass** [comment]
@zhenwenc Yes we are on our fork ! It's been working good for us, so nothing have been added, but we're open ! Be it issues, PRs, or whatever :-)
