### ISSUE TITLE
scala-tsi: alternative (maintained) library for generating Typescript interfaces

### ISSUE THREAD

**Issue by dhoepelman** [scala-ts/scala-ts#22]
Hi @miloszpp ,

About 2 years ago my company encountered your library and since it was pretty awesome, we tried to use it. Unfortunately we encountered [limitations in its design](https://github.com/code-star/scala-tsi/blob/master/doc/scala-ts.md), so we made [scala-tsi](https://github.com/code-star/scala-tsi), to solve the same problem in a different way.

I noticed you are currently not maintaining the project. Is it an idea to mention scala-tsi in the README as a maintained alternative?

**Comment by miloszpp** [comment]
Done

**Comment by dhoepelman** [comment]
Thanks!
